version: '3'
services:
  app:
    container_name: cryptoapp
    build:
      context: .
      args:
        - ARCHIVE_NAME=cryptoapp
        - APP_ENVIRONMENT=dev
    image: cryptoapp:latest
    depends_on:
      - database
    ports:
      - "8080:8080"
