version: '3'
services:
  app:
    container_name: cryptoapp
    build:
      context: .
      args:
        - ARCHIVE_NAME=cryptoapp
        - APP_ENVIRONMENT=dev
    image: cryptoapp:latest
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      -  DB_HOST=database
      -  DB_PORT=5432
      -  DB_DATABASE=crypto
      -  DB_USER=postgres
      -  DB_PASSWORD=Ilovemessi2149

  database:
    container_name: cryptodatabase
    image: 'postgres:14.1'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ilovemessi2149
      - POSTGRES_DB=crypto
    ports:
      - "5432:5432"