apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cicd-crypto
    app.kubernetes.io/instance: cicd-crypto-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: cicd-crypto
spec:
  selector:
    app: cicd-crypto
  type: LoadBalancer
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 8080
